export const countries = [
    { name: 'Afghanistan', code: '+93', country: 'AF' },
    { name: 'Albania', code: '+355', country: 'AL' },
    { name: 'Algeria', code: '+213', country: 'DZ' },
    { name: 'Andorra', code: '+376', country: 'AD' },
    { name: 'Angola', code: '+244', country: 'AO' },
    { name: 'Antigua and Barbuda', code: '+1-268', country: 'AG' },
    { name: 'Argentina', code: '+54', country: 'AR' },
    { name: 'Armenia', code: '+374', country: 'AM' },
    { name: 'Australia', code: '+61', country: 'AU' },
    { name: 'Austria', code: '+43', country: 'AT' },
    { name: 'Azerbaijan', code: '+994', country: 'AZ' },
    { name: 'Bahamas', code: '+1-242', country: 'BS' },
    { name: 'Bahrain', code: '+973', country: 'BH' },
    { name: 'Bangladesh', code: '+880', country: 'BD' },
    { name: 'Barbados', code: '+1-246', country: 'BB' },
    { name: 'Belarus', code: '+375', country: 'BY' },
    { name: 'Belgium', code: '+32', country: 'BE' },
    { name: 'Belize', code: '+501', country: 'BZ' },
    { name: 'Benin', code: '+229', country: 'BJ' },
    { name: 'Bhutan', code: '+975', country: 'BT' },
    { name: 'Bolivia', code: '+591', country: 'BO' },
    { name: 'Bosnia and Herzegovina', code: '+387', country: 'BA' },
    { name: 'Botswana', code: '+267', country: 'BW' },
    { name: 'Brazil', code: '+55', country: 'BR' },
    { name: 'Brunei', code: '+673', country: 'BN' },
    { name: 'Bulgaria', code: '+359', country: 'BG' },
    { name: 'Burkina Faso', code: '+226', country: 'BF' },
    { name: 'Burundi', code: '+257', country: 'BI' },
    { name: 'Cambodia', code: '+855', country: 'KH' },
    { name: 'Cameroon', code: '+237', country: 'CM' },
    { name: 'Canada', code: '+1', country: 'CA' },
    { name: 'Cape Verde', code: '+238', country: 'CV' },
    { name: 'Central African Republic', code: '+236', country: 'CF' },
    { name: 'Chad', code: '+235', country: 'TD' },
    { name: 'Chile', code: '+56', country: 'CL' },
    { name: 'China', code: '+86', country: 'CN' },
    { name: 'Colombia', code: '+57', country: 'CO' },
    { name: 'Comoros', code: '+269', country: 'KM' },
    { name: 'Congo', code: '+242', country: 'CG' },
    { name: 'Costa Rica', code: '+506', country: 'CR' },
    { name: 'Croatia', code: '+385', country: 'HR' },
    { name: 'Cuba', code: '+53', country: 'CU' },
    { name: 'Cyprus', code: '+357', country: 'CY' },
    { name: 'Czech Republic', code: '+420', country: 'CZ' },
    { name: 'Denmark', code: '+45', country: 'DK' },
    { name: 'Djibouti', code: '+253', country: 'DJ' },
    { name: 'Dominica', code: '+1-767', country: 'DM' },
    { name: 'Dominican Republic', code: '+1-809', country: 'DO' },
    { name: 'East Timor', code: '+670', country: 'TL' },
    { name: 'Ecuador', code: '+593', country: 'EC' },
    { name: 'Egypt', code: '+20', country: 'EG' },
    { name: 'El Salvador', code: '+503', country: 'SV' },
    { name: 'Equatorial Guinea', code: '+240', country: 'GQ' },
    { name: 'Eritrea', code: '+291', country: 'ER' },
    { name: 'Estonia', code: '+372', country: 'EE' },
    { name: 'Ethiopia', code: '+251', country: 'ET' },
    { name: 'Fiji', code: '+679', country: 'FJ' },
    { name: 'Finland', code: '+358', country: 'FI' },
    { name: 'France', code: '+33', country: 'FR' },
    { name: 'Gabon', code: '+241', country: 'GA' },
    { name: 'Gambia', code: '+220', country: 'GM' },
    { name: 'Georgia', code: '+995', country: 'GE' },
    { name: 'Germany', code: '+49', country: 'DE' },
    { name: 'Ghana', code: '+233', country: 'GH' },
    { name: 'Greece', code: '+30', country: 'GR' },
    { name: 'Grenada', code: '+1-473', country: 'GD' },
    { name: 'Guatemala', code: '+502', country: 'GT' },
    { name: 'Guinea', code: '+224', country: 'GN' },
    { name: 'Guinea-Bissau', code: '+245', country: 'GW' },
    { name: 'Guyana', code: '+592', country: 'GY' },
    { name: 'Haiti', code: '+509', country: 'HT' },
    { name: 'Honduras', code: '+504', country: 'HN' },
    { name: 'Hong Kong', code: '+852', country: 'HK' },
    { name: 'Hungary', code: '+36', country: 'HU' },
    { name: 'Iceland', code: '+354', country: 'IS' },
    { name: 'India', code: '+91', country: 'IN' },
    { name: 'Indonesia', code: '+62', country: 'ID' },
    { name: 'Iran', code: '+98', country: 'IR' },
    { name: 'Iraq', code: '+964', country: 'IQ' },
    { name: 'Ireland', code: '+353', country: 'IE' },
    { name: 'Israel', code: '+972', country: 'IL' },
    { name: 'Italy', code: '+39', country: 'IT' },
    { name: 'Ivory Coast', code: '+225', country: 'CI' },
    { name: 'Jamaica', code: '+1-876', country: 'JM' },
    { name: 'Japan', code: '+81', country: 'JP' },
    { name: 'Jordan', code: '+962', country: 'JO' },
    { name: 'Kazakhstan', code: '+7', country: 'KZ' },
    { name: 'Kenya', code: '+254', country: 'KE' },
    { name: 'Kiribati', code: '+686', country: 'KI' },
    { name: 'North Korea', code: '+850', country: 'KP' },
    { name: 'South Korea', code: '+82', country: 'KR' },
    { name: 'Kuwait', code: '+965', country: 'KW' },
    { name: 'Kyrgyzstan', code: '+996', country: 'KG' },
    { name: 'Laos', code: '+856', country: 'LA' },
    { name: 'Latvia', code: '+371', country: 'LV' },
    { name: 'Lebanon', code: '+961', country: 'LB' },
    { name: 'Lesotho', code: '+266', country: 'LS' },
    { name: 'Liberia', code: '+231', country: 'LR' },
    { name: 'Libya', code: '+218', country: 'LY' },
    { name: 'Liechtenstein', code: '+423', country: 'LI' },
    { name: 'Lithuania', code: '+370', country: 'LT' },
    { name: 'Luxembourg', code: '+352', country: 'LU' },
    { name: 'Macau', code: '+853', country: 'MO' },
    { name: 'Macedonia', code: '+389', country: 'MK' },
    { name: 'Madagascar', code: '+261', country: 'MG' },
    { name: 'Malawi', code: '+265', country: 'MW' },
    { name: 'Malaysia', code: '+60', country: 'MY' },
    { name: 'Maldives', code: '+960', country: 'MV' },
    { name: 'Mali', code: '+223', country: 'ML' },
    { name: 'Malta', code: '+356', country: 'MT' },
    { name: 'Marshall Islands', code: '+692', country: 'MH' },
    { name: 'Mauritania', code: '+222', country: 'MR' },
    { name: 'Mauritius', code: '+230', country: 'MU' },
    { name: 'Mexico', code: '+52', country: 'MX' },
    { name: 'Micronesia', code: '+691', country: 'FM' },
    { name: 'Moldova', code: '+373', country: 'MD' },
    { name: 'Monaco', code: '+377', country: 'MC' },
    { name: 'Mongolia', code: '+976', country: 'MN' },
    { name: 'Montenegro', code: '+382', country: 'ME' },
    { name: 'Morocco', code: '+212', country: 'MA' },
    { name: 'Mozambique', code: '+258', country: 'MZ' },
    { name: 'Namibia', code: '+264', country: 'NA' },
    { name: 'Nauru', code: '+674', country: 'NR' },
    { name: 'Nepal', code: '+977', country: 'NP' },
    { name: 'Netherlands', code: '+31', country: 'NL' },
    { name: 'New Zealand', code: '+64', country: 'NZ' },
    { name: 'Nicaragua', code: '+505', country: 'NI' },
    { name: 'Niger', code: '+227', country: 'NE' },
    { name: 'Nigeria', code: '+234', country: 'NG' },
    { name: 'Norway', code: '+47', country: 'NO' },
    { name: 'Oman', code: '+968', country: 'OM' },
    { name: 'Pakistan', code: '+92', country: 'PK' },
    { name: 'Palau', code: '+680', country: 'PW' },
    { name: 'Panama', code: '+507', country: 'PA' },
    { name: 'Papua New Guinea', code: '+675', country: 'PG' },
    { name: 'Paraguay', code: '+595', country: 'PY' },
    { name: 'Peru', code: '+51', country: 'PE' },
    { name: 'Philippines', code: '+63', country: 'PH' },
    { name: 'Poland', code: '+48', country: 'PL' },
    { name: 'Portugal', code: '+351', country: 'PT' },
    { name: 'Qatar', code: '+974', country: 'QA' },
    { name: 'Romania', code: '+40', country: 'RO' },
    { name: 'Russia', code: '+7', country: 'RU' },
    { name: 'Rwanda', code: '+250', country: 'RW' },
    { name: 'Saint Kitts and Nevis', code: '+1-869', country: 'KN' },
    { name: 'Saint Lucia', code: '+1-758', country: 'LC' },
    { name: 'Saint Vincent and the Grenadines', code: '+1-784', country: 'VC' },
    { name: 'Samoa', code: '+685', country: 'WS' },
    { name: 'San Marino', code: '+378', country: 'SM' },
    { name: 'Sao Tome and Principe', code: '+239', country: 'ST' },
    { name: 'Saudi Arabia', code: '+966', country: 'SA' },
    { name: 'Senegal', code: '+221', country: 'SN' },
    { name: 'Serbia', code: '+381', country: 'RS' },
    { name: 'Seychelles', code: '+248', country: 'SC' },
    { name: 'Sierra Leone', code: '+232', country: 'SL' },
    { name: 'Singapore', code: '+65', country: 'SG' },
    { name: 'Slovakia', code: '+421', country: 'SK' },
    { name: 'Slovenia', code: '+386', country: 'SI' },
    { name: 'Solomon Islands', code: '+677', country: 'SB' },
    { name: 'Somalia', code: '+252', country: 'SO' },
    { name: 'South Africa', code: '+27', country: 'ZA' },
    { name: 'Spain', code: '+34', country: 'ES' },
    { name: 'Sri Lanka', code: '+94', country: 'LK' },
    { name: 'Sudan', code: '+249', country: 'SD' },
    { name: 'Suriname', code: '+597', country: 'SR' },
    { name: 'Swaziland', code: '+268', country: 'SZ' },
    { name: 'Sweden', code: '+46', country: 'SE' },
    { name: 'Switzerland', code: '+41', country: 'CH' },
    { name: 'Syria', code: '+963', country: 'SY' },
    { name: 'Taiwan', code: '+886', country: 'TW' },
    { name: 'Tajikistan', code: '+992', country: 'TJ' },
    { name: 'Tanzania', code: '+255', country: 'TZ' },
    { name: 'Thailand', code: '+66', country: 'TH' },
    { name: 'Togo', code: '+228', country: 'TG' },
    { name: 'Tonga', code: '+676', country: 'TO' },
    { name: 'Trinidad and Tobago', code: '+1-868', country: 'TT' },
    { name: 'Tunisia', code: '+216', country: 'TN' },
    { name: 'Turkey', code: '+90', country: 'TR' },
    { name: 'Turkmenistan', code: '+993', country: 'TM' },
    { name: 'Tuvalu', code: '+688', country: 'TV' },
    { name: 'Uganda', code: '+256', country: 'UG' },
    { name: 'Ukraine', code: '+380', country: 'UA' },
    { name: 'United Arab Emirates', code: '+971', country: 'AE' },
    { name: 'United Kingdom', code: '+44', country: 'GB' },
    { name: 'United States', code: '+1', country: 'US' },
    { name: 'Uruguay', code: '+598', country: 'UY' },
    { name: 'Uzbekistan', code: '+998', country: 'UZ' },
    { name: 'Vanuatu', code: '+678', country: 'VU' },
    { name: 'Vatican City', code: '+379', country: 'VA' },
    { name: 'Venezuela', code: '+58', country: 'VE' },
    { name: 'Vietnam', code: '+84', country: 'VN' },
    { name: 'Yemen', code: '+967', country: 'YE' },
    { name: 'Zambia', code: '+260', country: 'ZM' },
    { name: 'Zimbabwe', code: '+263', country: 'ZW' }
];
